app/models.py
from app import db,login_manager

from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

class User(UserMixin, db.Model):
   
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(60), index=True, unique=True)
    username = db.Column(db.String(60), index=True, unique=True)
    password_hash = db.Column(db.String(128))

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute.')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        """
        Check if hashed password matches actual password
        """
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return '<User: {}>'.format(self.username)

# Set up user_loader
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class Music(db.Model):
    __tablename__ = "musics"

    id = db.Column(db.Integer,primary_key = True)
    title = db.Column(db.String(60))
    album = db.Column(db.String(60))
    artist = db.Column(db.String(60))
    url = db.Column(db.String(60))
    s3_upload = db.Column(db.Boolean,default=False)
    s3_url = db.Column(db.String(60))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    def __init__(self, title, album, artist,url):
        self.title = title
        self.album = album
        self.artist = artist
        self.url = url

    def __repr__(self):
        return "{}".format(self.url)

app/home/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, FileField


class MusicForm(FlaskForm):
    """
    Form for users to create new account
    """
    title = StringField('Title')
    artist = StringField('Artist')
    album = StringField('Album')
    music = FileField("Music")
    submit = SubmitField('Add')

app/__init__.py
from flask import Flask
from flask import request, render_template,redirect,url_for
from  flask_sqlalchemy import SQLAlchemy
from flask_uploads import UploadSet, AUDIO, configure_uploads
from flask_login import LoginManager
from flask_bootstrap import Bootstrap
from celery import Celery
from celery.utils.log import get_logger
import boto3
import os

from boto3.s3.transfer import S3Transfer

credentials = { 
    'aws_access_key_id': os.environ['AWS_CLIENT_ID'],
    'aws_secret_access_key': os.environ['AWS_CLIENT_SECRET']
}

client = boto3.client('s3', 'ap-south-1', **credentials)
transfer = S3Transfer(client)

#app config
app = Flask(__name__,template_folder="templates",static_url_path='/static')
app.config.from_object(os.environ['APP_SETTINGS'])
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

Bootstrap(app)

#configure database
db = SQLAlchemy(app)
login_manager = LoginManager()
login_manager.init_app(app) 
login_manager.login_message = "You must be logged in to view this page."
login_manager.login_view = "auth.login"

#configure uploads
music = UploadSet('music',AUDIO)
configure_uploads(app,music)

# Celery configuration
app.config['CELERY_BROKER_URL'] = os.environ['CELERY_BROKER_URL']
app.config['CELERY_RESULT_BACKEND'] = os.environ['CELERY_BROKER_BACKEND']

celery = Celery(app.name, broker=app.config['CELERY_BROKER_URL'])
celery.conf.update(app.config)
logger = get_logger(__name__)

#register blueprints
from .auth import auth as auth_blueprint
app.register_blueprint(auth_blueprint)

from .home import home as home_blueprint
app.register_blueprint(home_blueprint)

from app import models


@app.errorhandler(403)
def forbidden(error):
    return render_template('errors/403.html', title='Forbidden'), 403

@app.errorhandler(404)
def page_not_found(error):
    return render_template('errors/404.html', title='Page Not Found'), 404

@app.errorhandler(500)
def internal_server_error(error):
    return render_template('errors/500.html', title='Server Error'), 500

app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import routes

app/home/routes.py
from app import music,db,celery,logger,app,client,transfer
from app.models import Music
from flask_login import login_required,current_user
import os


from . import home
from .forms import MusicForm

from flask import request,render_template,redirect,url_for

@home.route("/",methods=['GET'])
def homepage():
    return render_template('home/index.html',title="Welcome")

@celery.task
def s3_upload(id,filename):
    try:
        music = Music.query.get_or_404(id)
        transfer.upload_file(os.path.dirname(os.path.dirname(os.path.abspath(__file__))) + '/static/music/' + filename, 'flask-public-store', str(music.id) + '/'+ music.title+'/'+filename,
                     extra_args={'ACL': 'public-read'})
        file_url = '%s/%s/%s' % (client.meta.endpoint_url, 'flask-public-store', str(music.id) + '/'+ music.title+'/'+filename)
        music.url = file_url
        with app.app_context():
            res = render_template('s3/index.html',song = music)
            logger.info(res)
            f = open(os.path.dirname(os.path.abspath(__file__)) + "/index.html","w")
            f.write(res)
            f.close()
            transfer.upload_file(os.path.dirname(os.path.dirname(os.path.abspath(__file__))) + '/static/css/style.css', 'flask-public-store', str(music.id) + '/'+ music.title+'/index.css',
                     extra_args={'ACL': 'public-read'})
            transfer.upload_file(os.path.dirname(os.path.abspath(__file__)) + '/index.html', 'flask-public-store', str(music.id) + '/'+ music.title+'/'+"index.html",
                     extra_args={'ACL': 'public-read'})
            file_url = '%s/%s/%s' % (client.meta.endpoint_url, 'flask-public-store', str(music.id) + '/'+ music.title+'/index.html')
            music.s3_url = file_url
            music.s3_upload = True
            db.session.commit()
        os.remove(os.path.dirname(os.path.dirname(os.path.abspath(__file__))) + '/static/music/' + filename)
    except Exception as e:
        logger.exception(e)

@home.route("/create", methods=['GET','POST'])
@login_required
def create_music():

    form = MusicForm()
    

    if form.is_submitted():
        
        try:
            filename = music.save(request.files['music'])
            url = music.url(filename)
            new_music = Music(request.form['title'],request.form['album'],request.form['artist'],url)
            new_music.user_id = current_user.get_id()
            db.session.add(new_music)
            db.session.commit()
            try:
                task = s3_upload.apply_async([new_music.id,filename])
            except Exception as e:
                print(e)
            return redirect(url_for('home.list_music'))
        except Exception as e:
            print(e)
    return render_template('home/add_music.html',form=form,title="Add Music")

@home.route("/list",methods=['GET'])
@login_required
def list_music():
    music = Music.query.filter_by(user_id = current_user.get_id()).all()
    return render_template('home/list_music.html',music = music)

@home.route('/music/<int:id>',methods=['GET','POST'])
def get_music(id):
    music = Music.query.get_or_404(id)
    print(music.s3_upload)
    return render_template('home/show_music.html',song = music)

@home.route("/delete/<int:id>",methods=['GET'])
def delete_music(id):
    music = Music.query.get_or_404(id)
    objects_to_delete = client.list_objects(Bucket="flask-public-store", Prefix="{}/{}/".format(music.id,music.title))

    delete_keys = {'Objects' : []}
    delete_keys['Objects'] = [{'Key' : k} for k in [obj['Key'] for obj in objects_to_delete.get('Contents', [])]]

    client.delete_objects(Bucket="flask-public-store", Delete=delete_keys)
    db.session.delete(music)
    db.session.commit()
    return redirect(url_for('home.list_music'))

app/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
        <title>{{ title }} | Music Management</title>
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>        
        <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
        <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
            <div class="container topnav">
              <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand topnav" href="{{ url_for('home.homepage') }}">Music Management</a>
              </div>
              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                  <ul class="nav navbar-nav navbar-right">
                      <li><a href="{{ url_for('home.list_music') }}">Home</a></li>
                      <li><a href="{{ url_for('auth.register') }}">Register</a></li>
                      <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                  </ul>
              </div>
            </div>
        </nav>
        <div class="wrapper">
          {% block body %}
          {% endblock %}
          <div class="push"></div>
        </div>
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <ul class="list-inline">
                            <li><a href="{{ url_for('home.list_music') }}">Home</a></li>
                            <li class="footer-menu-divider">⋅</li>
                            <li><a href="{{ url_for('auth.register') }}">Register</a></li>
                            <li class="footer-menu-divider">⋅</li>
                            <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
    </body>
    </html> 

app/templates/home/add_music.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}Add Music{% endblock %}
{% block body %}
<div class="content-section">
  <div class="center">
    <h1>Add song to your playlist</h1>
    <br/>
    {{ wtf.quick_form(form) }}
  </div>
</div>
{% endblock %}

app/templates/home/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Music management System</h1>
                    <h3>The best music player in the world!</h3>
                    <hr class="intro-divider">
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/list_music.html
{% extends "base.html" %}

{% block title %}
    <title>List Songs</title>
{% endblock %}

{% block body %}
    <div class="content-section">
        <div class="wrapper2">
            <div class="header">
                <h2>MMS-Music Managent System</h2>
            </div>
        </div>
        <a href="/create"><button class="btn btn-default add-button">Add Music</button></a>
	<table class="table table-bordered table-striped table-hover table-style">
		<thead>
			<tr class=" row flex-nowrap">
				<th class=" col-md-1 center-align">#</th>
				<th class=" col-md-2 center-align">Title</th>
				<th class=" col-md-2 center-align">Album</th>
				<th class= " col-md-3 center-align">Artist</th> 
				<th class=" col-md-4 center-align">Action</th>
			</tr>
		</thead>
		<tbody>
			{% for song in music %}
				<tr class=" row flex-nowrap">
					<td class=" col-md-1 center-align">{{ song.id }}</td>
					<td class=" col-md-3 center-align">{{ song.title }}</td>
					<td class=" col-md-3 center-align">{{ song.album }}</td>
					<td class= " col-md-3 center-align">{{ song.artist }}</td>
					<td class= " col-md-2 center-align">
						<a href="/music/{{ song.id }}">play</a>
						|
						<a href="/delete/{{ song.id }}">delete</a>
					</td>
				</tr>
            {% endfor %}
		</tbody> 
	</table>    
        <table>
            <tr>

            </tr>
        </table>
    </div>
{% endblock %}

app/templates/home/show_music.html
{% extends "base.html" %}

{% block body %}
<div class="content-section">
    <div class="wrapper2">
        <div class="header">
            <h2>MMS-Music Managent System</h2>
        </div>
    </div>
    <h1>{{song.title}}</h1>
    <hr>
    <b>{{ song.artist }}</b> | <b>{{ song.album }}</b>

    {% if song.s3_upload %}
        <h2>Public shareble link - {{ song.s3_url }}</h2>
    {% else %}
        <h2>Please wait for generated public URL</h2>
    {% endif %}

    <audio controls="controls">
        <source src="{{ song.url }}"/>
        Your browser doesnt't support audio , click <a href="{{ song.url }}">here</a> to download
    </audio>
</div>
{% endblock %}

app/templates/s3/index.html
<html>
    <head>
        <title>Streaming Page</title>
        <style>
            
            body, html {
                width: 100%;
                height: 100%;
            }

            body, h1, h2, h3 {
                font-family: "Lato", "Helvetica Neue", Helvetica, Arial, sans-serif;
                font-weight: 700;
            }

            a, .navbar-default .navbar-brand, .navbar-default .navbar-nav>li>a {
            color: #aec251;
            }

            a:hover, .navbar-default .navbar-brand:hover, .navbar-default .navbar-nav>li>a:hover {
            color: #687430;
            }

            footer {
                padding: 50px 0;
                background-color: #f8f8f8;
            }

            p.copyright {
                margin: 15px 0 0;
            }

            .alert-info {
                width: 50%;
                margin: auto;
                color: #687430;
                background-color: #e6ecca;
                border-color: #aec251;
            }

            .btn-default {
                border-color: #aec251;
                color: #aec251;
            }

            .btn-default:hover {
                background-color: #aec251;
            }

            .center {
                margin: auto;
                width: 50%;
                padding: 10px;
            }

            .content-section {
                padding: 50px 20px;
                border-top: 1px solid #e7e7e7;
            }

            .footer, .push {
            clear: both;
            height: 4em;
            }

            .intro-divider {
                width: 400px;
                border-top: 1px solid #f8f8f8;
                border-bottom: 1px solid rgba(0,0,0,0.2);
            }

            .intro-header {
                padding-top: 50px;
                padding-bottom: 50px;
                text-align: center;
                color: #f8f8f8;
                background: url(../img/intro-bg.jpg) no-repeat center center;
                background-size: cover;
                height: 100%;
            }

            .intro-message {
                position: relative;
                padding-top: 20%;
                padding-bottom: 20%;
            }

            .intro-message > h1 {
                margin: 0;
                text-shadow: 2px 2px 3px rgba(0,0,0,0.6);
                font-size: 5em;
            }

            .intro-message > h3 {
                text-shadow: 2px 2px 3px rgba(0,0,0,0.6);
            }

            .lead {
                font-size: 18px;
                font-weight: 400;
            }

            .topnav {
                font-size: 14px;
            }

            .wrapper {
            min-height: 100%;
            height: auto !important;
            height: 100%;
            margin: 0 auto -4em;
            }

            #wrapper2 {
                width: 100%;
            display: flex;
            justify-content: center;
            margin-top: 72px;
            margin-bottom: 36px;	
            }
            .header {
                text-align: center;
                width: 70%; 
                background: #aec251; 
                margin-top: 0px; 
                margin: auto;
                padding:15px 0px 15px 0px;}
            .header h2 {width: 100%; margin:auto; color: #FFFFFF;}

            .center-align {
                text-align: center;
            }

            .add-button {
                margin-left: 28px;
            }

            .table-style {
                width: 70%;
                margin: auto;
                margin-top: 20px;
            }
        </style>
    </head>
    <body>
        <div class="content-section">
            <div class="wrapper2">
                <div class="header">
                    <h2>MMS-Music Managent System</h2>
                </div>
            </div>
            <h1>{{song.title}}</h1>
            <hr>
            <b>{{ song.artist }}</b> | <b>{{ song.album }}</b>
                <br><br>
            <audio controls="controls">
                <source src="{{ song.url }}"/>
                Your browser doesnt't support audio , click <a href="{{ song.url }}">here</a> to download
            </audio>
        </div>
    </body>
</html>